language: python

matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      dist: xenial
      python: 3.7

before_install:
  - export BOTO_CONFIG=/dev/null

install:
  - pip install -r requirements.txt

script:
  - flake8
  - coverage run -m unittest -v

after_success:
  - coveralls