language: python

# have the docker service set up
services:
  - docker

env:
    global:
        - IMAGE_NAME=omarst910/cloudformation-seed
        - DOCKER_USERNAME=omarst910

# pre-checks before running the
# installation scripts
before_install:
    - version="$(sed -n 's/^ *version *= *//p' version.py | tr -d "'")"
    - echo ${version}
    - echo "Testing Docker Hub credentials"
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - echo "Docker Hub credentials are working"

# Build the image using the multistage dockerfile
# if the tests in the docker file fail
# the whole Travis build is considered a failure.
script:
    - docker build -f Dockerfile -t "${IMAGE_NAME}" .

after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" AND "$TRAVIS_PULL_REQUEST" = "false" ]]; then
      docker push "${IMAGE_NAME}:${version}" && docker push "${IMAGE_NAME}:latest" ;
    else
      git_sha="$(git rev-parse --short HEAD)"
      docker push "${IMAGE_NAME}:${git_sha}-${TRAVIS_BRANCH}" && docker push "${IMAGE_NAME}:${TRAVIS_BRANCH}"
    fi