language: python

matrix:
  include:
    - os: linux
      python: 3.6
    - os: linux
      dist: xenial
      python: 3.7

install:
  - python setup.py develop

script:
  - flake8
  - python -m unittest -v