---

AllConnectedAccounts: &CONNECTED_ACCOUNTS arn:aws:iam::000000000000:root,arn:aws:iam::111111111111:root,arn:aws:iam::222222222222:root

common-parameters:
  KmsDecryptLambdaArn: !StackOutput my-project-kms-decrypt-lambda.KmsDecryptLambdaArn

stacks:
  - name: my-project-kms-decrypt-lambda
    template: support/kms-parameters-lambda.cf.yaml
    parameters:
      LambdaSourceS3Key: !LambdaZip kmsParameters.zip

  - name: centralservices-s3-watchdog-lambda
    template: support/s3-watchdog-lambda.cf.yaml

  - name: centralservices-bucket-policy
    template: centralservices/bucket-policy.cf.yaml
    parameters:
      ConnectedAccountArns: *CONNECTED_ACCOUNTS

  - name: my-project
    template: my-project.cf.yaml
    parameters:
      VpcId: vpc-00000000
      PrivateSubnets: subnet-00000000,subnet-00000000
      ServerInstanceType: t2.small
      ServerAmi: ami-9d58b6ff


# vim: ts=2 sw=2 expandtab
