---
name: Release to Docker and PyPI
on:
  release:
    types:
      - published
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -Ur requirements-dev.txt
      - name: Prepare cloudformation-seed package
        run: |
          python setup.py develop
      - name: Lint with flake8
        run: |
          flake8
      - name: Run tests
        run: |
          python -m unittest -v
      - name: Install wheel and twine
        run: |
          python -m pip install --upgrade twine wheel
      - name: Build wheel and source
        run: |
          python setup.py sdist
          python setup.py bdist_wheel
      - name: Upload to PyPI
        run: |
          twine upload dist/*
